// <auto-generated />
using System;
using Bil_udlejning.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bil_udlejning.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231005111903_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bil_udlejning.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("car_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Bil_udlejning.Renting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Baby_chair")
                        .HasColumnType("bit");

                    b.Property<int>("Car_idId")
                        .HasColumnType("int");

                    b.Property<bool>("GPS")
                        .HasColumnType("bit");

                    b.Property<DateTime>("end_time")
                        .HasColumnType("datetime2");

                    b.Property<double>("price_sum")
                        .HasColumnType("float");

                    b.Property<DateTime>("start_time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Car_idId");

                    b.ToTable("Rentings");
                });

            modelBuilder.Entity("Bil_udlejning.Renting", b =>
                {
                    b.HasOne("Bil_udlejning.Car", "Car_id")
                        .WithMany()
                        .HasForeignKey("Car_idId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car_id");
                });
#pragma warning restore 612, 618
        }
    }
}
